- app.js
- config/database.js
- models/User.js
- models/data/users.js
> [MT-B2-15]

- models/Hotel.js
- models/data/hotels.js
Evidence:
Pendiente: 
- When my colleague adds the cities to the database, I will be able to complete this task by referencing said city to each Hotel.
> [MT-02-22]

- app.js
- controllers/hotel.js
- models/Hotel.js
- package-lock.json
- package.json
- routes/hotels.js
- routes/index.js
> [MT-02-23]

- models/Show.js
- models/data/shows.js
> [MT-02-25]

- controllers/hotel.js
- routes/hotels.js
> [MT-B2-28]

- controllers/hotel.js
- routes/hotels.js
> [MT-B2-30]

- controllers/show.js
- routes/index.js
- routes/show.js
> [MT-B2-32]

- controllers/show.js
- routes/show.js
> [MT-B2-34]

- controllers/show.js
- routes/show.js
> [MT-B2-36]

- controllers/hotel.js
- routes/hotels.js
> [MT-02-24]

- controllers/hotel.js
+ Added regex property to fix non-search of Uppercase & LowerCase letters.
> [FIX-MT-02-24]

- controllers/hotel.js
- package.json
- routes/hotels.js
- test/index.test.js
> MT-02-38 1/2 BACKEND

- package.json
- test/index.test.js
> [MT-01-37]

- controllers/hotel.js
- controllers/show.js
- package.json
- routes/hotels.js
- routes/show.js
- test/index.test.js
> Fix sprint2 mt 02 26

- controllers/hotel.js
- controllers/show.js
- package.json
- routes/hotels.js
- routes/show.js
- test/city.test.js
- test/index.test.js
Se separo el archivo ,se implemento forEach
> Fix mt 01 37

- controllers/hotel.js
- middlewares/validator.js
- routes/hotels.js
- schemas/hotels.js
- test/index.test.js
> [MT-02-40]

- controllers/hotel.js
- controllers/myHotels.js
- routes/index.js
- routes/myhotels.js
> [MT-02-42]

- controllers/myShows.js
- routes/index.js
- routes/myshows.js
> [MT-02-44]

- config/passport.js
- controllers/user.js
- middlewares/accountExistsSignIn.js
- middlewares/mustSignIn.js
- package-lock.json
- package.json
- routes/users.js
- schemas/signin.js
> [MT-02-46]

- controllers/user.js
- routes/users.js
> [MT-02-50]

- routes/show.js
- schemas/shows.js
> [MT-02-52]

- test/index.test.js
> [MT-02-54]

- test/index.test.js
HOTFIX:
- The error was not displayed when you entered an invalid HOTEL ID.
Evidence of fix:
> [FIX-MT-02-54]

- config/passport.js
- config/responses.js
- middlewares/verifyHotel.js
- middlewares/verifyShow.js
- routes/hotels.js
- routes/show.js
> [FIX-SPRINT-4] #BACKEND TOKEN

- routes/show.js
> [FIX-SPRINT-4]

- config/responses.js
- middlewares/verifyCity.js
- middlewares/verifyItinerary.js
- routes/city.js
- routes/itinerary.js
- schemas/itinerary.js
> Fix mt 01 52 mt 01 54

- controllers/comment.js
- models/Comment.js
- models/data/comments.js
- routes/comment.js
- routes/index.js
- routes/itinerary.js
**Evidence:**
**Evidence:**
**Evidence:**
> [MT-02-57]

- controllers/comment.js
- controllers/user.js
- models/Comment.js
- models/data/comments.js
- routes/comment.js
- routes/index.js
- routes/itinerary.js
- schemas/comments.js
Fixed search of comments by specific show id.
> [FIX-MT-02-57]

- models/data/reactions.js
Se termino de subir los demás scrips faltantes
> Fix mt 01 55

- controllers/comment.js
- controllers/hotel.js
> [mt-02-58]
